/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Blender3D (https://sketchfab.com/Blender3D)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/0d62f4d3676545c88ec8523213c055dd
title: Minecraft Diamond Axe
*/

import * as THREE from "three";
import { type GLTF } from "three-stdlib";
import { type ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

import axeModel from "./axe.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1001_1: THREE.Mesh;
    Mesh_1001_2: THREE.Mesh;
  };
  materials: {
    material_2: THREE.MeshStandardMaterial;
    material_3: THREE.MeshStandardMaterial;
  };
};

export default function Axe(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(axeModel) as unknown as GLTFResult;
  return (
    <group dispose={null} {...props}>
      <group rotation={[0, Math.PI / 1.8, -0.3]} scale={0.5}>
        <mesh
          geometry={nodes.Mesh_1001_1.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Mesh_1001_2.geometry}
          material={materials.material_3}
        />
      </group>
    </group>
  );
}

useGLTF.preload(axeModel);
