managePackageManagerVersions: true

packages:
  - apps/*
  - demos/*
  - packages/*

catalog:
  react: ^18.3.1
  react-dom: ^18.3.1
  three: ^0.165.0
  '@react-three/fiber': ^8.17.5
  '@react-three/drei': ^9.109.5
  '@react-three/postprocessing': ^2.16.2
  '@react-three/rapier': ^1.4.0
  '@react-three/cannon': ^6.6.0
  '@react-three/csg': ^3.2.0
  '@pmndrs/branding': ^0.0.8
  '@pmndrs/assets': ^1.6.0
  '@react-spring/three': ^9.7.3
  '@react-spring/web': ^9.7.4
  framer-motion: ^10.18.0
  zustand: ^3.7.2
  valtio: ^1.13.2
  leva: ^0.9.35
  maath: ^0.10.8
  postprocessing: ^6.36.0
  r3f-perf: ^7.2.1
  lamina: ^1.1.23
  three-stdlib: ^2.32.2
  meshline: ^3.3.1
  styled-components: ^6.1.1
  react-colorful: ^5.6.1
  react-icons: ^4.12.0
  antd: ^5.20.1
  '@headlessui/react': ^1.7.19
  '@heroicons/react': ^1.0.6
  wouter: ^2.12.1
  '@splinetool/loader': ^0.9.526
  '@splinetool/r3f-spline': ^1.0.2
  nice-color-palettes: ^3.0.0
  lodash-es: ^4.17.21
  '@babel/runtime': ^7.25.0
  babel-plugin-glsl: ^1.0.0
  '@types/react': ^18.3.3
  '@types/react-dom': ^18.3.0
  '@types/three': ^0.165.0
  '@vitejs/plugin-react': ^4.3.1
  typescript: ^5.5.4
  vite: ^5.4.0

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
