pmOnFail: download
shamefullyHoist: true

packages:
  - apps/*
  - demos/*
  - packages/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

patchedDependencies:
  '@splinetool/loader@1.12.98': patches/@splinetool__loader@1.12.98.patch
