pmOnFail: download
shamefullyHoist: true

packages:
  - apps/*
  - demos/*
  - packages/*

allowBuilds:
  esbuild: true
  unrs-resolver: true

patchedDependencies:
  '@splinetool/loader@0.9.153': patches/@splinetool__loader@0.9.153.patch
