/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car.glb --transform
Author: cuadot (https://sketchfab.com/cuadot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/car-acccd15d4e454399a39dbe40f4f6df71
Title: Car
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, Wireframe } from '@react-three/drei'

import carModel from './car.glb?url'

export function Model(opts) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(carModel)
  const { actions } = useAnimations(animations, group)

  useEffect(() => {
    actions['Idle.1'].reset().play()
  }, [actions])

  return (
    <group ref={group} position-y={-1.25}>
      <primitive rotation={[-Math.PI / 2, 0, 0]} object={nodes._rootJoint} />
      <skinnedMesh geometry={nodes.Object_78.geometry} material={materials.Mat_Robot} skeleton={nodes.Object_78.skeleton}>
        <Wireframe {...opts} />
      </skinnedMesh>
    </group>
  )
}

useGLTF.preload(carModel)
