/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 crow.glb --transform --types
Author: LostBoyz2078 (https://sketchfab.com/LostModels2025)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/crow-2001eaf8e667446c969a69ca5b1b65ae
Title: Crow
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import React, { useEffect, useRef, type JSX } from "react";
import type {
  AnimationClip,
  Bone,
  Group,
  MeshStandardMaterial,
  SkinnedMesh,
} from "three";
import type { GLTF } from "three-stdlib";
import { SkeletonUtils } from "three-stdlib";

import crowModel from "./crow-transformed.glb?url";

type ActionName = "GltfAnimation 0";

interface GLTFAction extends AnimationClip {
  name: ActionName;
}

type GLTFResult = GLTF & {
  nodes: {
    Object_7: SkinnedMesh;
    Object_10: SkinnedMesh;
    GLTF_created_0_rootJoint: Bone;
  };
  materials: {
    M_CrowWings: MeshStandardMaterial;
    M_CrowBody: MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Crow(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<Group>(null);
  const { scene, animations } = useGLTF(crowModel);
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone) as unknown as GLTFResult;
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["GltfAnimation 0"]?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null} scale={0.006}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes.GLTF_created_0_rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials.M_CrowWings}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.M_CrowBody}
          skeleton={nodes.Object_10.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload(crowModel);
