/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 cobra.glb --transform
*/

import * as THREE from "three";
import { type GLTF } from "three-stdlib";
import { type ThreeElements } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

import cobraModel from "./cobra-transformed.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    Material2: THREE.Mesh;
    Material2007: THREE.Mesh;
    Material2009: THREE.Mesh;
    Material2010: THREE.Mesh;
    Material2012: THREE.Mesh;
    Material2018: THREE.Mesh;
    Material2029: THREE.Mesh;
    Material2037: THREE.Mesh;
    Material2040: THREE.Mesh;
    Material2066: THREE.Mesh;
    Material2067: THREE.Mesh;
    Material2068: THREE.Mesh;
    Material2071: THREE.Mesh;
    Material2078: THREE.Mesh;
    Material2079: THREE.Mesh;
    Material3004: THREE.Mesh;
  };
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial;
    Suede_Green: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshStandardMaterial;
    Translucent_Glass_Corrugated: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshStandardMaterial;
    Metal_Silver: THREE.MeshStandardMaterial;
    PaletteMaterial006: THREE.MeshStandardMaterial;
    MT__15_2: THREE.MeshStandardMaterial;
    MT__15: THREE.MeshStandardMaterial;
    MT__15_1_0: THREE.MeshStandardMaterial;
    MT__15_1: THREE.MeshStandardMaterial;
    Groundcover_BarkChips: THREE.MeshStandardMaterial;
    Groundcover_Rock_Crushed_Multi_1: THREE.MeshStandardMaterial;
    MT__15__1: THREE.MeshStandardMaterial;
  };
};

export function Model({
  color,
  ...props
}: ThreeElements["group"] & { color?: string }) {
  const { nodes, materials } = useGLTF(cobraModel) as unknown as GLTFResult;
  return (
    <group scale={0.025} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2.geometry}
        material={materials.PaletteMaterial001}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2007.geometry}
        material={materials.Suede_Green}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2009.geometry}
        material={materials.PaletteMaterial002}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2010.geometry}
        material={materials.PaletteMaterial003}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2012.geometry}
        material={materials.PaletteMaterial004}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2018.geometry}
        material={materials.Translucent_Glass_Corrugated}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2029.geometry}
        material={materials.PaletteMaterial005}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2037.geometry}
        material={materials.Metal_Silver}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2040.geometry}
        material={materials.PaletteMaterial006}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2066.geometry}
        material={materials.MT__15_2}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2067.geometry}
        material={materials.MT__15}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2068.geometry}
        material={materials.MT__15_1_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2071.geometry}
        material={materials.MT__15_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2078.geometry}
        material={materials.Groundcover_BarkChips}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material2079.geometry}
        material={materials.Groundcover_Rock_Crushed_Multi_1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Material3004.geometry}
        material={materials.MT__15__1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload(cobraModel);
