// model by eon/sketchfab https://sketchfab.com/3d-models/elven-ranger-statue-71aec2d9f7724ae09992435ce8ff7258
// Component auto-generated by GLTFJSX: https://github.com/react-spring/gltfjsx

import { createRoot } from 'react-dom/client'
import './styles.css'
import App from './App'

createRoot(document.querySelector('#root')).render(<App />)
