/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model.glb --transform -t 
Files: model.glb [1.53MB] > D:\examples\examples\ascii\public\model-transformed.glb [170.48KB] (89%)
Author: Omar Faruq Tawsif (https://sketchfab.com/omarfaruqtawsif32)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/still-life-based-on-heathers-artwork-abbcbfa6be104fcc8dc8d5b07b607719
Title: Still life, Based on Heather's artwork
*/

import { useGLTF } from "@react-three/drei";
import { JSX } from "react";
import { MeshBasicMaterial } from "three";
import { GLTF } from "three-stdlib";
import { Mesh } from "three/src/objects/Mesh.js";
import modelUrl from "./model-transformed.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    Object_5: Mesh;
    Object_7: Mesh;
    Object_9: Mesh;
    Object_11: Mesh;
    Object_13: Mesh;
    Object_15: Mesh;
    Object_17: Mesh;
    Object_19: Mesh;
    Object_21: Mesh;
    Object_23: Mesh;
  };
  materials: {
    board_n_knife: MeshBasicMaterial;
    food: MeshBasicMaterial;
    ["Material.001"]: MeshBasicMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(modelUrl) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Empty_10" position={[0, 2.021, 0]}>
            <group name="Cube_0" position={[0, -2.021, 0]}>
              <mesh
                name="Object_5"
                geometry={nodes.Object_5.geometry}
                material={materials.board_n_knife}
              />
            </group>
            <group name="Cube001_1" position={[-0.493, -1.786, -0.004]}>
              <mesh
                name="Object_7"
                geometry={nodes.Object_7.geometry}
                material={materials.food}
              />
            </group>
            <group
              name="Cube003_2"
              position={[0.524, -1.854, 0.268]}
              rotation={[0, -0.185, 0]}
            >
              <mesh
                name="Object_9"
                geometry={nodes.Object_9.geometry}
                material={materials.food}
              />
            </group>
            <group
              name="Cube004_3"
              position={[0.416, -1.937, 1.166]}
              rotation={[0, 0.538, 0]}
            >
              <mesh
                name="Object_11"
                geometry={nodes.Object_11.geometry}
                material={materials.food}
              />
            </group>
            <group
              name="Cube007_4"
              position={[0.524, -1.854, 0.268]}
              rotation={[0, -0.185, 0]}
            >
              <mesh
                name="Object_13"
                geometry={nodes.Object_13.geometry}
                material={materials.food}
              />
            </group>
            <group
              name="Cylinder001_5"
              position={[0.836, -1.865, -0.089]}
              rotation={[-0.814, -0.367, 1.263]}
              scale={1.092}
            >
              <mesh
                name="Object_15"
                geometry={nodes.Object_15.geometry}
                material={materials.board_n_knife}
              />
            </group>
            <group name="Plane_6" position={[0.785, -2.048, 0.524]}>
              <mesh
                name="Object_17"
                geometry={nodes.Object_17.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Sphere001_7"
              position={[-0.151, -1.728, 0.752]}
              rotation={[1.326, 0.129, 0.512]}
            >
              <mesh
                name="Object_19"
                geometry={nodes.Object_19.geometry}
                material={materials.food}
              />
            </group>
            <group
              name="Sphere002_8"
              position={[0.157, -1.713, 0.648]}
              rotation={[1.439, 0.055, -0.988]}
            >
              <mesh
                name="Object_21"
                geometry={nodes.Object_21.geometry}
                material={materials.food}
              />
            </group>
            <group
              name="Sphere003_9"
              position={[0.505, -1.713, -0.739]}
              rotation={[1.716, -0.025, 0.615]}
              scale={0.968}
            >
              <mesh
                name="Object_23"
                geometry={nodes.Object_23.geometry}
                material={materials.food}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(modelUrl);
