import * as THREE from "three";
import { useRef, useState } from "react";
import { easing } from "maath";
import { Canvas, useFrame, type ThreeElements } from "@react-three/fiber";
import {
  useGLTF,
  Center,
  Caustics,
  Environment,
  Lightformer,
  RandomizedLight,
  PerformanceMonitor,
  AccumulativeShadows,
  MeshTransmissionMaterial,
} from "@react-three/drei";
import { type GLTF } from "three-stdlib";

import glassModel from "./glass-transformed.glb?url";

type GLTFResult = GLTF & {
  nodes: {
    cake: THREE.Mesh;
    straw_1: THREE.Mesh;
    straw_2: THREE.Mesh;
    straw001_1: THREE.Mesh;
    straw001_2: THREE.Mesh;
    flowers: THREE.Mesh;
    fork: THREE.Mesh;
    glass: THREE.Mesh;
    glass_back: THREE.Mesh;
    glass_inner: THREE.Mesh;
  };
  materials: {
    FruitCakeSlice_u1_v1: THREE.MeshStandardMaterial;
    straw_2: THREE.MeshStandardMaterial;
    straw_1: THREE.MeshStandardMaterial;
    "draifrawer_u1_v1.001": THREE.MeshStandardMaterial;
    ForkAndKnivesSet001_1K: THREE.MeshStandardMaterial;
  };
};

const innerMaterial = new THREE.MeshStandardMaterial({
  transparent: true,
  opacity: 1,
  color: "black",
  roughness: 0,
  side: THREE.FrontSide,
  blending: THREE.AdditiveBlending,
  polygonOffset: true,
  polygonOffsetFactor: 1,
  envMapIntensity: 2,
});

export default function App() {
  const [perfSucks, degrade] = useState(false);
  return (
    <Canvas
      shadows
      dpr={[1, perfSucks ? 1.5 : 2]}
      eventSource={document.getElementById("root")!}
      eventPrefix="client"
      camera={{ position: [20, 0.9, 20], fov: 26 }}
    >
      {/** PerfMon will detect performance issues */}
      <PerformanceMonitor onDecline={() => degrade(true)} />
      <color attach="background" args={["#f0f0f0"]} />
      <group position={[0, -0.5, 0]} rotation={[0, -0.75, 0]}>
        <Scene />
        <AccumulativeShadows
          frames={100}
          alphaTest={0.75}
          opacity={0.8}
          color="red"
          scale={20}
          position={[0, -0.005, 0]}
        >
          <RandomizedLight
            amount={8}
            radius={6}
            ambient={0.5}
            intensity={Math.PI}
            position={[-1.5, 2.5, -2.5]}
            bias={0.001}
          />
        </AccumulativeShadows>
      </group>
      <Env perfSucks={perfSucks} />
    </Canvas>
  );
}

/*
Kit-bash auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.glb --transform
Licenses: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Authors:
  matousekfoto (https://sketchfab.com/matousekfoto) (Fruit Cake Slice)
    https://sketchfab.com/3d-models/fruit-cake-slice-7b9a33386eab4dd986aa0980054ead3c
  Felix Yadomi (https://sketchfab.com/felixyadomi) (Cute milkshake)
    https://sketchfab.com/3d-models/cute-milkshake-3ba52a41b4b248df953684861d9e7a20
  Second Studio (https://sketchfab.com/kayaaku) (Dry flower)
    https://sketchfab.com/3d-models/dry-flower-ff0005d6eb4d4077bd08b8992299c45c
  CDcruz (https://sketchfab.com/cdcruz) (Ikea - Pokal Glass Cups)
    https://sketchfab.com/3d-models/ikea-pokal-glass-cups-21837e54a14346aa900e1ae719779b86
*/
const causticsLegacyProps = {
  backfaces: true,
  focus: [0, -1.2, 0],
  frustum: 1.75,
  backfaceIor: 1.26,
};

function Scene(props: ThreeElements["group"]) {
  const { nodes, materials } = useGLTF(glassModel) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        rotation={[0, -0.5, 0]}
        geometry={nodes.cake.geometry}
        material={materials.FruitCakeSlice_u1_v1}
      />
      <mesh
        castShadow
        geometry={nodes.straw_1.geometry}
        material={materials.straw_2}
      />
      <mesh
        castShadow
        geometry={nodes.straw_2.geometry}
        material={materials.straw_1}
      />
      <mesh
        castShadow
        position={[0, -0.005, 0]}
        geometry={nodes.straw001_1.geometry}
        material={materials.straw_2}
      />
      <mesh
        castShadow
        position={[0, -0.005, 0]}
        geometry={nodes.straw001_2.geometry}
        material={materials.straw_1}
      />
      <Center rotation={[0, -0.4, 0]} position={[-1, -0.01, -2]} top>
        <mesh
          scale={1.2}
          castShadow
          geometry={nodes.flowers.geometry}
          material={materials["draifrawer_u1_v1.001"]}
        />
      </Center>
      <mesh
        castShadow
        geometry={nodes.fork.geometry}
        material={materials.ForkAndKnivesSet001_1K}
        material-color="#999"
      />

      <Caustics
        // The Caustics type declares these as required, though the component
        // itself defaults both to false — passing them explicitly matches
        // what this example already got implicitly.
        causticsOnly={false}
        backside={false}
        color={[1, 0.8, 0.8]}
        lightSource={[-1.2, 3, -2]}
        intensity={0.003}
        worldRadius={0.26 / 10}
        ior={0.9}
        // @react-three/drei's CausticsProps type no longer lists these (the
        // Caustics API changed under it), but the component still forwards
        // unrecognized props onward, so passing them keeps prior behaviour.
        {...causticsLegacyProps}
      >
        <mesh castShadow receiveShadow geometry={nodes.glass.geometry}>
          <MeshTransmissionMaterial
            backside
            backsideThickness={0.1}
            thickness={0.05}
            chromaticAberration={0.05}
            anisotropicBlur={1}
            clearcoat={1}
            clearcoatRoughness={1}
            envMapIntensity={2}
          />
        </mesh>
      </Caustics>

      {/** Some hacks to get some back face reflections, otherwise the glass would look fake */}
      <mesh
        scale={[0.95, 1, 0.95]}
        geometry={nodes.glass_back.geometry}
        material={innerMaterial}
      />
      <mesh geometry={nodes.glass_inner.geometry} material={innerMaterial} />
    </group>
  );
}

function Env({ perfSucks }: { perfSucks: boolean }) {
  const ref = useRef<THREE.Group>(null!);
  useFrame((state, delta) => {
    // Animate the environment as well as the camera
    if (!perfSucks) {
      easing.damp3(
        // maath's damp3 is typed for Vector3, but it only ever reads/writes
        // x/y/z, which Euler also has, so this keeps the original behaviour.
        ref.current.rotation as unknown as THREE.Vector3,
        [Math.PI / 2, 0, state.clock.elapsedTime / 5 + state.pointer.x],
        0.2,
        delta,
      );
      easing.damp3(
        state.camera.position,
        [
          Math.sin(state.pointer.x / 4) * 9,
          1.25 + state.pointer.y,
          Math.cos(state.pointer.x / 4) * 9,
        ],
        0.5,
        delta,
      );
      state.camera.lookAt(0, 0, 0);
    }
  });
  // Runtime environments can be too slow on some systems, better safe than sorry with PerfMon
  return (
    <Environment
      frames={perfSucks ? 1 : Infinity}
      preset="city"
      resolution={256}
      background
      backgroundBlurriness={0.8}
    >
      <Lightformer
        intensity={4}
        rotation-x={Math.PI / 2}
        position={[0, 5, -9]}
        scale={[10, 10, 1]}
      />
      <Lightformer
        intensity={4}
        rotation-x={Math.PI / 2}
        position={[0, 5, -9]}
        scale={[10, 10, 1]}
      />
      <group rotation={[Math.PI / 2, 1, 0]}>
        {[2, -2, 2, -4, 2, -5, 2, -9].map((x, i) => (
          <Lightformer
            key={i}
            intensity={1}
            rotation={[Math.PI / 4, 0, 0]}
            position={[x, 4, i * 4]}
            scale={[4, 1, 1]}
          />
        ))}
        <Lightformer
          intensity={0.5}
          rotation-y={Math.PI / 2}
          position={[-5, 1, -1]}
          scale={[50, 2, 1]}
        />
        <Lightformer
          intensity={0.5}
          rotation-y={Math.PI / 2}
          position={[-5, -1, -1]}
          scale={[50, 2, 1]}
        />
        <Lightformer
          intensity={0.5}
          rotation-y={-Math.PI / 2}
          position={[10, 1, 0]}
          scale={[50, 2, 1]}
        />
      </group>
      <group ref={ref}>
        <Lightformer
          intensity={5}
          form="ring"
          color="red"
          rotation-y={Math.PI / 2}
          position={[-5, 2, -1]}
          scale={[10, 10, 1]}
        />
      </group>
    </Environment>
  );
}
