import * as THREE from "three";
import React, { forwardRef, useRef } from "react";
import { Canvas, useFrame, type ThreeElements } from "@react-three/fiber";
import {
  OrbitControls,
  Environment,
  useGLTF,
  Float,
  PivotControls,
  QuadraticBezierLine,
  Backdrop,
  ContactShadows,
  useEnvironment,
  type QuadraticBezierLineRef,
} from "@react-three/drei";

import astronautModel from "./assets/Astronaut-transformed.glb?url";
import spaceshipModel from "./assets/Low-Poly-Spaceship.gltf?url";

// Auto-generated by: https://github.com/pmndrs/gltfjsx
const Spaceman = forwardRef<THREE.Mesh, ThreeElements["mesh"]>(
  ({ children, ...props }, ref) => {
    const { meshes, materials } = useGLTF(astronautModel);
    const environment = useEnvironment({ preset: "city" });
    return (
      <mesh
        castShadow
        receiveShadow
        ref={ref}
        {...props}
        geometry={meshes.Astronaut_mesh.geometry}
        material={materials.Astronaut_mat}
        material-roughness={0}
        material-envMap={environment}
        material-envMapIntensity={0}
        dispose={null}
      >
        {children}
      </mesh>
    );
  },
);

// Low Poly Spaceship by EdwinRC, licensed under CC BY 2.0.
const Ship = forwardRef<THREE.Group, ThreeElements["group"]>((props, ref) => {
  const { meshes, materials } = useGLTF(spaceshipModel);
  const environment = useEnvironment({ preset: "city" });
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={meshes.Cube005.geometry}
        material={materials.Mat0}
        material-roughness={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={meshes.Cube005_1.geometry}
        material={materials.Mat1}
        material-roughness={0}
        material-color="black"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={meshes.Cube005_2.geometry}
        material={materials.Mat2}
        material-roughness={0}
        material-envMap={environment}
        material-envMapIntensity={0.2}
        material-color="black"
      />
      <mesh
        castShadow
        receiveShadow
        geometry={meshes.Cube005_3.geometry}
        material={materials.Window_Frame}
        material-roughness={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={meshes.Cube005_4.geometry}
        material={materials.Mat4}
        material-roughness={0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={meshes.Cube005_6.geometry}
        material={materials.Window}
        material-roughness={0}
      />
    </group>
  );
});

interface CableProps {
  start: React.RefObject<THREE.Object3D>;
  end: React.RefObject<THREE.Object3D>;
  v1?: THREE.Vector3;
  v2?: THREE.Vector3;
  mid?: THREE.Vector3;
}

function Cable({
  start,
  end,
  v1 = new THREE.Vector3(),
  v2 = new THREE.Vector3(),
  mid = new THREE.Vector3(),
}: CableProps) {
  const ref = useRef<QuadraticBezierLineRef>(null!);
  useFrame(() => {
    const from = start.current.getWorldPosition(v1);
    const to = end.current.getWorldPosition(v2);
    ref.current.setPoints(from, to, mid.set(to.x, from.y, to.z));
  }, 0);
  return (
    <QuadraticBezierLine
      ref={ref}
      start={[0, 0, 0]}
      end={[0, 0, 0]}
      lineWidth={3}
      color="#ff2060"
    />
  );
}

function StudioBackdrop() {
  const environment = useEnvironment({ preset: "city" });
  return (
    <>
      <Backdrop
        castShadow
        receiveShadow={undefined}
        floor={2}
        position={[0, -0.5, -3]}
        scale={[50, 10, 4]}
      >
        <meshStandardMaterial
          color="#353540"
          envMap={environment}
          envMapIntensity={0.1}
        />
      </Backdrop>
      <Environment map={environment} />
    </>
  );
}

export default function App() {
  const spaceman = useRef<THREE.Object3D>(null!);
  const ship = useRef<THREE.Group>(null!);
  return (
    <Canvas shadows camera={{ position: [0, 1.5, 3] }}>
      <ambientLight intensity={0.2 * Math.PI} />
      <directionalLight
        position={[-10, 0, -5]}
        intensity={Math.PI}
        color="red"
      />
      <directionalLight
        position={[-1, -2, -5]}
        intensity={0.2 * Math.PI}
        color="#0c8cbf"
      />
      <spotLight
        position={[5, 0, 5]}
        intensity={2.5 * Math.PI}
        decay={0}
        penumbra={1}
        angle={0.35}
        castShadow
        color="#0c8cbf"
      />

      <Float scale={0.75} position={[0, 0.65, 0]} rotation={[0, 0.6, 0]}>
        <PivotControls
          anchor={[0, 0.7, 0.09]}
          depthTest={true}
          scale={0.5}
          lineWidth={2}
        >
          <Ship ref={ship} />
        </PivotControls>
      </Float>

      <Float
        position={[1, 1.1, -0.5]}
        rotation={[Math.PI / 3.5, 0, 0]}
        rotationIntensity={4}
        floatIntensity={6}
        speed={1.5}
      >
        <Spaceman scale={0.2}>
          <object3D position={[-0.6, 2, 0]} ref={spaceman} />
        </Spaceman>
      </Float>
      <Cable start={ship} end={spaceman} />
      <StudioBackdrop />
      <ContactShadows position={[0, -0.485, 0]} scale={5} blur={1.5} far={1} />
      <OrbitControls makeDefault />
    </Canvas>
  );
}
